const categories = [
    { 
        category: "Televisions", 
        short_name: "Televizory", 
        image_url: "https://storage.yandexcloud.net/step2002sharp/televisory.jpg" 
    },
    { 
        category: "Laptops", 
        short_name: "Noutbuki", 
        image_url: "https://storage.yandexcloud.net/step2002sharp/nounbuki.jpeg" 
    },
    { 
        category: "Smartphones", 
        short_name: "Smartfony", 
        image_url: "https://storage.yandexcloud.net/step2002sharp/telefony.jpg" 
    },
    { 
        category: "Tablets", 
        short_name: "Planshety", 
        image_url: "https://storage.yandexcloud.net/step2002sharp/tablets.jpg" 
    },
    { 
        category: "Home Appliances", 
        short_name: "Bytovaya-tehnika", 
        image_url: "https://storage.yandexcloud.net/step2002sharp/bytovaya.jpg" 
    },
    { 
        category: "Headphones", 
        short_name: "Nauschniki", 
        image_url: "https://storage.yandexcloud.net/step2002sharp/headphones.jpg" 
    },
    { 
        category: "Smart Watches", 
        short_name: "Smart-chasy", 
        image_url: "https://storage.yandexcloud.net/step2002sharp/watches.jpg" 
    }
];

const products = [
    {
        name: "Ноутбук Acer Aspire 5",
        price: 79999,
        image_url: "https://example.com/images/laptop1.jpg",
        description: "Бюджетный ноутбук с высокими характеристиками.",
        slug: "acer-aspire-5",
        category: categories.find((cat) => cat.short_name === "Noutbuki"),
        },
        {
        name: "HP Pavilion 15",
        price: 99999,
        image_url: "https://example.com/images/laptop2.jpg",
        description: "Мощный ноутбук для работы и развлечений.",
        slug: "hp-pavilion-15",
        category: categories.find((cat) => cat.short_name === "Noutbuki"),
        },
        {
        name: "Samsung Galaxy S21",
        price: 69999,
        image_url: "https://example.com/images/smartphone1.jpg",
        description: "Смартфон с великолепной камерой и экраном.",
        slug: "samsung-galaxy-s21",
        category: categories.find((cat) => cat.short_name === "Smartfony"),
        },
        {
        name: "Apple iPhone 13",
        price: 79999,
        image_url: "https://example.com/images/smartphone2.jpg",
        description: "Популярный смартфон с передовыми технологиями.",
        slug: "apple-iphone-13",
        category: categories.find((cat) => cat.short_name === "Smartfony"),
        },
        {
        name: "Apple iPad Air",
        price: 39999,
        image_url: "https://example.com/images/tablet1.jpg",
        description: "Лёгкий и мощный планшет для любых задач.",
        slug: "apple-ipad-air",
        category: categories.find((cat) => cat.short_name === "Planshety"),
        },
        {
        name: "Samsung Galaxy Tab S7",
        price: 29999,
        image_url: "https://example.com/images/tablet2.jpg",
        description: "Планшет с высоким разрешением экрана.",
        slug: "samsung-galaxy-tab-s7",
        category: categories.find((cat) => cat.short_name === "Planshety"),
        },
        {
        name: "Sony WH-1000XM4",
        price: 19999,
        image_url: "https://example.com/images/headphones1.jpg",
        description: "Наушники с лучшим шумоподавлением.",
        slug: "sony-wh-1000xm4",
        category: categories.find((cat) => cat.short_name === "Nauschniki"),
        },
        {
        name: "Bose QuietComfort 35 II",
        price: 14999,
        image_url: "https://example.com/images/headphones2.jpg",
        description: "Комфортные наушники для длительного использования.",
        slug: "bose-quietcomfort-35-ii",
        category: categories.find((cat) => cat.short_name === "Nauschniki"),
        },
        {
        name: "Apple Watch Series 7",
        price: 24999,
        image_url: "https://example.com/images/smartwatch1.jpg",
        description: "Продвинутые умные часы для активного образа жизни.",
        slug: "apple-watch-series-7",
        category: categories.find((cat) => cat.short_name === "Smart-chasy"),
        },
        {
        name: "Samsung Galaxy Watch 4",
        price: 19999,
        image_url: "https://example.com/images/smartwatch2.jpg",
        description: "Умные часы с множеством функций.",
        slug: "samsung-galaxy-watch-4",
        category: categories.find((cat) => cat.short_name === "Smart-chasy"),
        },
        {
        name: "LG OLED55CXPUA Alexa Built-In CX Series",
        price: 129999,
        image_url: "https://example.com/images/tv1.jpg",
        description: "Телевизор с отличным качеством изображения.",
        slug: "lg-oled55cxpua",
        category: categories.find((cat) => cat.short_name === "Televizory"),
        },
        {
        name: "Samsung QN65Q80TAFXZA Alexa Built-In QLED TV",
        price: 89999,
        image_url: "https://example.com/images/tv2.jpg",
        description: "Качественный QLED телевизор для дома.",
        slug: "samsung-qn65q80taf",
        category: categories.find((cat) => cat.short_name === "Televizory"),
        },
        {
        name: "Dell XPS 13",
        price: 119999,
        image_url: "/images/laptop3.jpg",
        description: "Компактный ноутбук премиум-класса.",
        slug: "dell-xps-13",
        category: categories.find((cat) => cat.short_name === "Noutbuki"),
        },
        {
        name: "Google Pixel 6a",
        price: 49999,
        image_url: "/images/smartphone3.jpg",
        description: "Элегантный смартфон с чистым Android.",
        slug: "google-pixel-6a",
        category: categories.find((cat) => cat.short_name === "Smartfony"),
        },
        {
        name: "Microsoft Surface Pro 7",
        price: 34999,
        image_url: "/images/tablet3.jpg",
        description: "Универсальный планшет для работы и учёбы.",
        slug: "microsoft-surface-pro-7",
        category: categories.find((cat) => cat.short_name === "Planshety"),
        },
        {
        name: "JBL Tune 500BT",
        price: 8999,
        image_url: "/images/headphones3.jpg",
        description: "Беспроводные наушники с отличным звучанием.",
        slug: "jbl-tune-500bt",
        category: categories.find((cat) => cat.short_name === "Nauschniki"),
        },
        {
        name: "Fitbit Versa 3",
        price: 14999,
        image_url: "/images/smartwatch3.jpg",
        description: "Умные часы для здоровья и фитнеса.",
        slug: "fitbit-versa-3",
        category: categories.find((cat) => cat.short_name === "Smart-chasy"),
        },
        {
        name: "Sony X900H",
        price: 79999,
        image_url: "https://example.com/images/tv3.jpg",
        description: "4K HDR телевизор с великолепным качеством изображения.",
        slug: "sony-x900h",
        category: categories.find((cat) => cat.short_name === "Televizory"),
        },
        {
        name: "Razer Blade Stealth",
        price: 139999,
        image_url: "https://example.com/images/laptop4.jpg",
        description: "Мощный ноутбук для игр и работы.",
        slug: "razer-blade-stealth",
        category: categories.find((cat) => cat.short_name === "Noutbuki"),
        },
        {
        name: "Lenovo IdeaPad Flex 5",
        price: 84999,
        image_url: "https://example.com/images/laptop5.jpg",
        description: "Универсальный ноутбук с поворотным экраном.",
        slug: "lenovo-ideapad-flex-5",
        category: categories.find((cat) => cat.short_name === "Noutbuki"),
        },
        {
        name: "Xiaomi Mi 11",
        price: 59999,
        image_url: "https://example.com/images/smartphone4.jpg",
        description: "Смартфон с мощным процессором и ярким экраном.",
        slug: "xiaomi-mi-11",
        category: categories.find((cat) => cat.short_name === "Smartfony"),
        },
        {
        name: "Huawei MatePad Pro",
        price: 27999,
        image_url: "https://example.com/images/tablet4.jpg",
        description: "Планшет с профессиональными возможностями.",
        slug: "huawei-matepad-pro",
        category: categories.find((cat) => cat.short_name === "Planshety"),
        },
        {
        name: "Sennheiser HD 450BT",
        price: 12999,
        image_url: "https://example.com/images/headphones4.jpg",
        description: "Наушники с активным шумоподавлением.",
        slug: "sennheiser-hd-450bt",
        category: categories.find((cat) => cat.short_name === "Nauschniki"),
        },
        {
        name: "Garmin Venu Sq",
        price: 19999,
        image_url: "https://example.com/images/smartwatch4.jpg",
        description: "Умные часы с функциями мониторинга здоровья.",
        slug: "garmin-venu-sq",
        category: categories.find((cat) => cat.short_name === "Smart-chasy"),
        },
        {
        name: "Asus VivoBook 15",
        price: 74999,
        image_url: "https://example.com/images/laptop6.jpg",
        description: "Доступный ноутбук для повседневного использования.",
        slug: "asus-vivobook-15",
        category: categories.find((cat) => cat.short_name === "Noutbuki"),
        },
        {
        name: "OnePlus Nord 2",
        price: 49999,
        image_url: "https://example.com/images/smartphone5.jpg",
        description: "Смартфон с отличным соотношением цены и качества.",
        slug: "oneplus-nord-2",
        category: categories.find((cat) => cat.short_name === "Smartfony"),
        },
        {
        name: "Lenovo Tab P11",
        price: 31999,
        image_url: "https://example.com/images/tablet5.jpg",
        description: "Планшет с большим экраном для работы и развлечений.",
        slug: "lenovo-tab-p11",
        category: categories.find((cat) => cat.short_name === "Planshety"),
        },
        {
        name: "Anker Soundcore Life Q20",
        price: 10999,
        image_url: "https://example.com/images/headphones5.jpg",
        description: "Наушники с активным шумоподавлением и качественным звуком.",
        slug: "anker-soundcore-life-q20",
        category: categories.find((cat) => cat.short_name === "Nauschniki"),
        },
        {
        name: "Amazfit Bip U Pro",
        price: 17999,
        image_url: "https://example.com/images/smartwatch5.jpg",
        description: "Умные часы с функциями GPS и мониторинга здоровья.",
        slug: "amazfit-bip-u-pro",
        category: categories.find((cat) => cat.short_name === "Smart-chasy"),
        },
        {
        name: "TCL 55P615",
        price: 74999,
        image_url: "https://example.com/images/tv4.jpg",
        description: "Ультратонкий 4K UHD телевизор с функцией Smart TV.",
        slug: "tcl-55p615",
        category: categories.find((cat) => cat.short_name === "Televizory"),
        },
        {
        name: "MSI Modern 14",
        price: 89999,
        image_url: "https://example.com/images/laptop7.jpg",
        description: "Лёгкий ноутбук с мощными характеристиками для работы и развлечений.",
        slug: "msi-modern-14",
        category: categories.find((cat) => cat.short_name === "Noutbuki"),
        },
        {
        name: "Realme GT Master Edition",
        price: 57999,
        image_url: "https://example.com/images/smartphone6.jpg",
        description: "Смартфон с выдающимся дизайном и высокой производительностью.",
        slug: "realme-gt-master-edition",
        category: categories.find((cat) => cat.short_name === "Smartfony"),
        },
        {
        name: "Amazon Fire HD 10",
        price: 24999,
        image_url: "https://example.com/images/tablet6.jpg",
        description: "Планшет с большим экраном и доступной ценой.",
        slug: "amazon-fire-hd-10",
        category: categories.find((cat) => cat.short_name === "Planshety"),
        },
        {
        name: "Beats Solo Pro",
        price: 13999,
        image_url: "https://example.com/images/headphones6.jpg",
        description: "Наушники премиум-класса с активным шумоподавлением.",
        slug: "beats-solo-pro",
        category: categories.find((cat) => cat.short_name === "Nauschniki"),
        },
        {
        name: "Huawei Watch Fit",
        price: 15999,
        image_url: "/images/smartwatch6.jpg",
        description: "Лёгкие умные часы с длительным временем работы.",
        slug: "huawei-watch-fit",
        category: categories.find((cat) => cat.short_name === "Smart-chasy"),
        },
        {
        name: "Philips 55PUS8505",
        price: 69999,
        image_url: "/images/tv5.jpg",
        description: "Телевизор с поддержкой HDR10+ и Ambilight.",
        slug: "philips-55pus8505",
        category: categories.find((cat) => cat.short_name === "Televizory"),
        },
        {
        name: "HP Envy x360",
        price: 109999,
        image_url: "https://example.com/images/laptop8.jpg",
        description: "Элегантный ноутбук-трансформер для профессионалов.",
        slug: "hp-envy-x360",
        category: categories.find((cat) => cat.short_name === "Noutbuki"),
        },
        {
        name: "Vivo V21e",
        price: 64999,
        image_url: "https://example.com/images/smartphone7.jpg",
        description: "Смартфон с отличной камерой и стильным дизайном.",
        slug: "vivo-v21e",
        category: categories.find((cat) => cat.short_name === "Smartfony"),
        },
        {
        name: "Samsung Galaxy Tab A7",
        price: 23999,
        image_url: "https://example.com/images/tablet7.jpg",
        description: "Планшет с ярким экраном и поддержкой многозадачности.",
        slug: "samsung-galaxy-tab-a7",
        category: categories.find((cat) => cat.short_name === "Planshety"),
        },
        {
        name: "Sony WH-CH510",
        price: 9999,
        image_url: "https://example.com/images/headphones7.jpg",
        description: "Беспроводные наушники с длительным временем автономной работы.",
        slug: "sony-wh-ch510",
        category: categories.find((cat) => cat.short_name === "Nauschniki"),
        },
        {
        name: "Xiaomi Mi Band 6",
        price: 12999,
        image_url: "https://example.com/images/smartwatch7.jpg",
        description: "Фитнес-браслет с мониторингом активности и здоровья.",
        slug: "xiaomi-mi-band-6",
        category: categories.find((cat) => cat.short_name === "Smart-chasy"),
        },
        {
        name: "Xiaomi Mi TV P1",
        price: 85999,
        image_url: "https://example.com/images/tv6.jpg",
        description: "Смарт ТВ с высоким качеством изображения и голосовым управлением.",
        slug: "xiaomi-mi-tv-p1",
        category: categories.find((cat) => cat.short_name === "Televizory"),
        },     
    ]
 export {
    categories,
    products
 }
